# Generated by Django 4.2.7 on 2025-11-15 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('important', models.BooleanField(default=False, verbose_name='Важный элемент')),
            ],
            options={
                'verbose_name': 'Элемент контекста',
                'verbose_name_plural': 'Элементы контекста',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
                ('score', models.FloatField(blank=True, default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Оценка качества')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('suggested_by_reviewer', models.BooleanField(default=False, verbose_name='Создана ревьювером')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('context', models.ManyToManyField(blank=True, to='corrections.contextelement', verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Объект/Гипотеза',
                'verbose_name_plural': 'Объекты/Гипотезы',
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'PENDING - Ожидает проверки'), (1, 'APPROVED - Подтверждена'), (2, 'INVALID - Аннулирована')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('scope_id', models.IntegerField(default=0, verbose_name='Область видимости')),
                ('hypotheses', models.ManyToManyField(blank=True, related_name='correction_hypotheses', to='corrections.item', verbose_name='Гипотезы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_subject', to='corrections.item', verbose_name='Корректируемый объект')),
            ],
            options={
                'verbose_name': 'Корректировка',
                'verbose_name_plural': 'Корректировки',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope_id', 'status'], name='corrections_scope_i_278724_idx'), models.Index(fields=['created_at'], name='corrections_created_fde721_idx'), models.Index(fields=['updated_at'], name='corrections_updated_1f9cdc_idx')],
            },
        ),
    ]
