# Generated by Django 4.2.7 on 2025-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING - Ожидает проверки'), (1, 'APPROVED - Подтверждена'), (2, 'INVALID - Аннулирована')], default=0, verbose_name='Статус'),
        ),
    ]
