# Generated by Django 4.2.7 on 2025-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0002_alter_correction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='hypotheses',
            field=models.ManyToManyField(related_name='correction_hypotheses', to='corrections.item', verbose_name='Гипотезы'),
        ),
    ]
